




<CreateAccountScreen>:
    header_buttons : header_buttons
    find_my_location_button : find_my_location_button
    registration_form : registration_form

    BoxLayout:
        orientation: 'vertical' 

        
        MDBoxLayout:
            size_hint: 1 , 0.8
            md_bg_color: chex("#B9B4C7")
            radius: root.adaptive_radius

            ScrollView:
                size_hint: 1 , 1

                MDGridLayout:
                    size_hint: 1, None
                    adaptive_height: True
                    cols: 1
                    padding: [20, 0 , 20 , 0]

                    Widget:
                        size_hint: 1, None
                        height: root.widget_25_height
                    
                    HeaderButtons:
                        id: header_buttons
                    

                    Widget:
                        size_hint: 1, None
                        height: root.widget_15_height
        

                    BoxLayout:
                        size_hint: 1, None
                        orientation: 'horizontal'
                        height: root.login_logo_height


                        Image:
                            allow_stretch: True
                            keep_ratio: True
                            source: root.create_account_logo
                            size_hint: (0.5, 1)

                        BoxLayout:
                            size_hint: (0.5, 1)
                            orientation: 'vertical'
                            spacing: 0
                            padding: [0 , 0 , 20 , 0]
                            
                            Widget:
                                size_hint: (1, 0.2)
                            Label:
                                size_hint: (1 , 0.25)
                                font_size: root.create_account_title_font_size
                                halign: 'left'
                                valign: 'middle'  # optional, keeps vertical centering
                                text_size: self.size
                                font_name: 'p_extrabold'
                                text: 'Create Your Account'
                                color: chex("#352F44")
                            Widget:
                                size_hint: (1, 0.05)
                            Label:
                                size_hint: (1, 0.50)
                                font_size: root.create_account_content_font_size
                                halign: 'left'
                                valign: 'top'
                                text_size: self.size
                                font_name: 'p_light'
                                color: chex("#352F44")
                                text: 'Get started with "Your Connection, Your Control"—track router issues, monitor tickets, and manage your account seamlessly.'


                    Widget:
                        size_hint: 1, None
                        height: root.widget_15_height
 
                    Label:
                        size_hint: 1, None
                        height: root.widget_35_height
                        font_size: root.h1_font_size
                        halign: 'left'
                        valign: 'middle'  # optional, keeps vertical centering
                        text_size: self.size
                        font_name: 'p_bold'
                        text: 'Verify Service Availability'
                        color: chex("#FFFFFF")
 

                    Label:
                        size_hint: 1 , None
                        text_size: self.width, None 
                        height: self.texture_size[1] + root.widget_15_height  # Auto height based on wrapped content
                        font_size: root.h2_font_size
                        halign: 'left'
                        valign: 'top'
                        font_name: 'p_light'
                        color: chex("#352F44")
                        text: "We need your location first to confirm that your home or office falls within our coverage area. This ensures you get the speeds and packages we can actually deliver, helps us show you the right pricing, and lets us schedule installation quickly if you're in range."

                    Widget:
                        size_hint: 1, None
                        height: root.widget_15_height

                    BoxLayout:
                        size_hint: 1, None
                        height: root.widget_35_height

                        AppButton:
                            id: find_my_location_button
                            size_hint: 0.4 , 1
                            on_release: root.find_my_location()

                            Label:
                                size_hint: 1, 1
                                text: "Find My Location"
                                font_size: root.find_my_location_button_font_size
                                font_name: 'p_bold'

                        Label:
                            size_hint: 0.6, 1
                            text: "123.1023 , 13.0123"
                            font_size: root.find_my_location_button_font_size
                            font_name: 'p_mediumitalic'
                            color: chex("#5C5470")

                    Widget:
                        size_hint: 1, None
                        height: root.widget_15_height
                    
                    MDBoxLayout:
                        id: registration_form
                        orientation: 'vertical'
                        size_hint: 1, None
                        adaptive_height: True 


                    Widget:
                        size_hint: 1, None
                        height: 30


        BoxLayout:
            size_hint: (1, 0.2)
            orientation: 'horizontal'
            padding: 10

            Image:
                allow_stretch: True
                keep_ratio: True
                source: root.login_logo
                size_hint: (0.5, 1)
            
            BoxLayout:
                size_hint: (0.5, 1)
                orientation: 'vertical'
                spacing: 0
                
                Widget:
                    size_hint: (1, 0.2)
                Label:
                    size_hint: (1 , 0.2)
                    font_size: root.info_title_font_size
                    halign: 'left'
                    valign: 'middle'  # optional, keeps vertical centering
                    text_size: self.size
                    font_name: 'p_regular'
                    text: 'Your Connection, Your Control'
                Widget:
                    size_hint: (1, 0.05)
                Label:
                    size_hint: (1, 0.55)
                    font_size: root.info_content_font_size
                    halign: 'left'
                    valign: 'top'
                    text_size: self.size
                    font_name: 'p_extralight'
                    text: 'Stay in the loop—track your router issues, monitor ticket updates, and manage your account, all in one smart app designed to keep your internet running smoothly.'
                    



<AccountRegistrationFormLayout>:
    
    first_name_input: first_name_input
    last_name_input: last_name_input
    middle_name_input: middle_name_input
    email_input: email_input
    street_input : street_input
    barangay_input: barangay_input
    city_input: city_input
    phone1_input: phone1_input
    phone2_input: phone2_input
    phone3_input: phone3_input
    username_input: username_input
    password_input: password_input
    confirm_password_input: confirm_password_input
    date_of_birth_input : date_of_birth_input

    opacity: 0
    size_hint: (1 , None)
    adaptive_height: True
    orientation: 'vertical'


    AppButton:
        size_hint: (1 , None)
        height: root.widget_8_height
        radius: [3]
        md_bg_color: chex("5C5470") 
    
    Widget:
        size_hint: 1, None
        height: 15

    Label:
        size_hint: 1, None
        text_size: self.width, None 
        height: self.texture_size[1]  # Auto height based on wrapped content
        font_size: root.h1_font_size
        halign: 'left'
        valign: 'middle'  # optional, keeps vertical centering 
        font_name: 'p_bold'
        text: 'Enter your account details below to complete registration.'
        color: chex("#352F44") 
        halign: 'left'
        valign: 'top'

    Widget:
        size_hint: 1, None
        height: 15

    Label:
        size_hint: 1, None
        height: 35
        font_size: root.h2_font_size
        halign: 'left'
        valign: 'middle'  # optional, keeps vertical centering
        text_size: self.size
        font_name: 'p_bold'
        text: 'Personal Information'
        color: chex("#FFFFFF")
 

    Widget:
        size_hint: 1, None
        height: root.widget_8_height

    OneLineInput:
        id: first_name_input
        size_hint: 1, None
        height: 35

    Widget:
        size_hint: 1, None
        height: root.widget_8_height

    OneLineInput: 
        id: middle_name_input
        size_hint: 1, None
        height: 35

    Widget:
        size_hint: 1, None
        height: root.widget_8_height

    OneLineInput: 
        id: last_name_input
        size_hint: 1, None
        height: 35

    Widget:
        size_hint: 1, None
        height: root.widget_8_height

    OneLineInput: 
        id: email_input
        size_hint: 1, None
        height: 35


    Widget:
        size_hint: 1, None
        height: root.widget_8_height

    AppButton: 
        id: date_of_birth_input
        size_hint: 1, None
        height: 35
        on_release: root.select_date()
        md_bg_color: chex('#5C5470')

        Label:
            size_hint: 1, 1
            text: "  Select birth date"
            font_size: root.h3_font_size
            font_name: 'p_light'
            text_size: self.size
            halign: 'left'
            valign: 'middle'  # optional, keeps vertical centering
            color: chex("#FFFFFF")

    Widget:
        size_hint: 1, None
        height: 15

    Label:
        size_hint: 1, None
        height: 35
        font_size: root.h2_font_size
        halign: 'left'
        valign: 'middle'  # optional, keeps vertical centering
        text_size: self.size
        font_name: 'p_bold'
        text: 'Address Information'
        color: chex("#FFFFFF")
 
    Widget:
        size_hint: 1, None
        height: root.widget_8_height

    OneLineInput: 
        id: street_input
        size_hint: 1, None
        height: 35

    Widget:
        size_hint: 1, None
        height: root.widget_8_height

    OneLineInput: 
        id: barangay_input
        size_hint: 1, None
        height: 35

    Widget:
        size_hint: 1, None
        height: root.widget_8_height

    AppButton: 
        id: city_input
        size_hint: 1, None
        height: 35

        Label:
            size_hint: 1, 1
            text: root.selected_city
            font_size: root.h2_font_size
            font_name: 'p_bold'

    Widget:
        size_hint: 1, None
        height: 15

    Label:
        size_hint: 1, None
        height: 35
        font_size: root.h2_font_size
        halign: 'left'
        valign: 'middle'  # optional, keeps vertical centering
        text_size: self.size
        font_name: 'p_bold'
        text: 'Contact Information'
        color: chex("#FFFFFF")
 
    Widget:
        size_hint: 1, None
        height: root.widget_8_height

    OneLineInput: 
        id: phone1_input
        size_hint: 1, None
        height: 35

    Widget:
        size_hint: 1, None
        height: root.widget_8_height

    OneLineInput: 
        id: phone2_input
        size_hint: 1, None
        height: 35

    Widget:
        size_hint: 1, None
        height: root.widget_8_height

    OneLineInput: 
        id: phone3_input
        size_hint: 1, None
        height: 35



    Widget:
        size_hint: 1, None
        height: 15

    Label:
        size_hint: 1, None
        height: 35
        font_size: root.h2_font_size
        halign: 'left'
        valign: 'middle'  # optional, keeps vertical centering
        text_size: self.size
        font_name: 'p_bold'
        text: 'Valid I.D. Information Upload'
        color: chex("#FFFFFF")
    
    Widget:
        size_hint: 1, None
        height: root.widget_8_height

    BoxLayout:
        size_hint: 1, None
        height: 125
        orientation: 'horizontal'

        Widget:
            size_hint: 1, 1
        
        AppButton:
            size_hint: (None , 1)
            width: root.valid_id_image_width
            md_bg_color: chex('#352F44')
            on_release: root.upload_image()
 
            Image:
                size_hint: 0.9, 0.9
                source: root.valid_id_image_source
                allow_stretch: False
                keep_ratio: False
                pos_hint: {'center_x' : 0.5, 'center_y' : 0.5}




        Widget:
            size_hint: 1, 1


    Widget:
        size_hint: 1, None
        height: 15

    Label:
        size_hint: 1, None
        height: 35
        font_size: root.h2_font_size
        halign: 'left'
        valign: 'middle'  # optional, keeps vertical centering
        text_size: self.size
        font_name: 'p_bold'
        text: 'Account Security Information'
        color: chex("#FFFFFF")


    Widget:
        size_hint: 1, None
        height: root.widget_8_height

    OneLineInput: 
        id: username_input
        size_hint: 1, None
        height: 35

    Widget:
        size_hint: 1, None
        height: root.widget_8_height

    OneLineInput: 
        id: password_input
        size_hint: 1, None
        height: 35

    Widget:
        size_hint: 1, None
        height: root.widget_8_height

    OneLineInput: 
        id: confirm_password_input
        size_hint: 1, None
        height: 35


    Widget:
        size_hint: 1, None
        height: 15

    Label:
        size_hint: 1, None
        height: 35
        font_size: root.h2_font_size
        halign: 'left'
        valign: 'middle'  # optional, keeps vertical centering
        text_size: self.size
        font_name: 'p_bold'
        text: 'Terms & Privacy'
        color: chex("#352F44")


    BoxLayout:
        size_hint: 1, None
        height: 33
        orientation: 'horizontal'
        spacing: 5
        
        CustomCheckbox:
            size_hint: None, None
            size: root.checkbox_size
            
        LabelClickable:
            size_hint: 1, 1
            font_size: root.h4_font_size
            halign: 'left'
            valign: 'middle'  # optional, keeps vertical centering
            text_size: self.size
            font_name: 'p_italic'
            text: '[u]I have read and agree to the [Terms of Service].'
            color: chex("#352F44")
            markup: True
    
    Widget:
        size_hint: 1, None
        height: 5
    
    BoxLayout:
        size_hint: 1, None
        height: 33
        orientation: 'horizontal'
        spacing: 5
        
        CustomCheckbox:
            size_hint: None, None
            size: root.checkbox_size
            
        LabelClickable:
            size_hint: 1, 1
            font_size: root.h4_font_size
            halign: 'left'
            valign: 'middle'  # optional, keeps vertical centering
            text_size: self.size
            font_name: 'p_italic'
            text: '[u]I have read and agree to the [Privacy Policy].'
            color: chex("#352F44")
            markup: True

    Widget:
        size_hint: 1, None
        height: 15




    BoxLayout:
        size_hint: 1, None
        height: 30
        orientation: 'horizontal'

        Widget:
            size_hint: 0.45, 1
        
        AppButton:
            size_hint: 0.55, 1
            md_bg_color: chex("352F44")

            Label:
                size_hint: 1, 1
                text: 'Register Account'
                font_size: root.h3_font_size
                font_name: 'p_bold'
                color: chex("#FAF0E6")





    Widget:
        size_hint: 1, None
        height: 15



<CustomCheckbox@MDCheckbox>:
    theme_text_color: "Custom"    
    selected_color:   chex("#352F44")

    # Control the actual icon glyphs for each state
    checkbox_icon_normal: 'checkbox-blank-outline'
    checkbox_icon_down:   'checkbox-marked-outline'
    color_inactive : chex("#B9B4C7")



<CityDropdownButton>: 
    Label:
        size_hint: 1, 1
        text: root.text
        font_name: "p_regular"
        font_size: root.text_font_size
        color: chex("#FFFFFF")
 
