





LOGIN_SCREEN = 'login_screen'

LOGIN_SCREEN_PIN_LOGIN_SCREEN = 'pinlogin'  
LOGIN_SCREEN_REGISTER_ACCOUNT_SCREEN = 'registerlogin'
LOGIN_SCREEN_REGISTER_PIN_SCREEN = 'registerpin'

LOGIN_SCREEN_ACTION_REGISTER = 'register'  
LOGIN_SCREEN_ACTION_FORGOT_PIN = 'forgotpin'
LOGIN_SCREEN_FIRST_ACTION = 'verify_user'
LOGIN_SCREEN_ACTION_PIN = 'pin'

HOME_SCREEN = 'home'
HOME_SCREEN_DASHBOARD_SCREEN = 'dashboard'
HOME_SCREEN_TICKETLIST_SCREEN = 'ticket'
HOME_SCREEN_ACCOUNT_SCREEN = 'account'
HOME_SCREEN_TRANSACT_SCREEN = 'transact'


