
<HomeScreen>:
    
    account_header : account_header
    headline : headline
    router : router
    tickets : tickets
    account : account
        
    ScrollView:
        size_hint: (1, 1)
        effect_cls: 'ScrollEffect'
        do_scroll_x: False
        bar_width: 0  # Optional: hide bar
        scroll_type: ['content']  # No overscroll bar effects

        MDGridLayout:
            size_hint: (1 , None)
            adaptive_height: True
            cols: 1 

            AccountHeader:
                id: account_header
                size_hint: ( 1, None)
                height: root.header_height

            MDBoxLayout:
                size_hint: (1 , None)
                orientation: 'vertical'
                adaptive_height: True
                padding: root.home_screen_padding
                canvas.before:
                    Color:
                        rgba: chex("#B9B4C7")
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: root.home_screen_radius
                
                Widget:
                    size_hint: (1, None)
                    height: root.home_screen_spacing
                    
                HeadlineLayout:
                    id: headline
                    size_hint: (1, None)

                Widget:
                    size_hint: (1, None)
                    height: root.home_screen_spacing
                
                RouterLayout:
                    id: router
                    size_hint: (1, None)
                
                Widget:
                    size_hint: (1, None)
                    height: root.home_screen_spacing

                TicketsLayout:
                    id: tickets
                    size_hint: (1, None)
                    
                Widget:
                    size_hint: (1, None)
                    height: root.home_screen_spacing

                AccountLayout:
                    id: account
                    size_hint: (1, None)


<AccountHeader>:
    logout_icon : logout_icon
    edit_icon : edit_icon
    refresh_icon : refresh_icon
    
    AppButton:
        md_bg_color: chex("#5C5470")
        radius: root.account_image_radius
        size_hint: None, None
        size: root.account_image_size, root.account_image_size
        pos_hint: {'center_x': 0.5,'center_y': 0.4}

        Label:
            size_hint: 1, 1
            font_size: root.account_fname_font_size
            font_name: 'p_extrabold'
            text: "N"

            # canvas.before:
            #     Color:
            #         rgba: chex("#5C5470")
            #     RoundedRectangle:
            #         pos: self.pos
            #         size: self.size
            #         radius: [16]

    MDBoxLayout:
        orientation: 'vertical'
        adaptive_size: True
        pos_hint: {'top': 0.95 , 'x' : 0.015}  # Only affect vertical positioning
        spacing: root.buttons_spacing
        


        TappableImage:
            id: logout_icon
            size_hint: (None , None)
            allow_stretch: True

        
        TappableImage:
            id: edit_icon
            size_hint: (None , None)
            allow_stretch: True

        
        TappableImage:
            id: refresh_icon
            size_hint: (None , None)
            allow_stretch: True

    

<SectionIconLayout>:
    height: 30
    clickable_image : clickable_image

    Widget:
        size_hint: (0.1, 1) if not root.is_half_padding_left else (0.05 , 1)
    
    Image:
        source: root.sec_icon
        allow_stretch: True
        keep_ration: True
        size_hint: None, 1
        width: 20
    
    Widget:
        size_hint: (0.8, 1) if not root.is_half_padding_left else (0.85 , 1)

    ClickableImage:
        id: clickable_image
        size_hint: None, 1
        width: 40
        opacity: 1 if root.display_additional else 0
    
    Widget:
        size_hint: 0.1, 1


<ClickableImage>:
    clickable_label : clickable_label

    Label:
        pos_hint: {'center_x': 0.5,'center_y': 0.5}
        size_hint: 1, 1
        font_size: root.adaptable_font_size
        font_name: "p_bold"
        text: root.main_text
        markup: True
        opacity: 0.7 if root.has_comming_soon else 1
    
    CustomClickableLabel:
        id : clickable_label
        pos_hint: {'center_x': 0.5,'center_y': 0.5}
        size_hint: 1, 1
        font_size: root.adaptable_font_size
        font_name: "p_bold"
        text: "comming soon"
        opacity: 1 if root.has_comming_soon else 0

        on_release: root.additional_event() if root.additional_event else None


        canvas.before:
            PushMatrix
            Rotate:
                angle: root.set_angle
                origin: self.center
        canvas.after:
            PopMatrix
