

<AddPlanScreen>:

    holder : holder
    add_plan_information : add_plan_information
    
    MDFloatLayout:
        id: holder  
        size_hint: (1 , 1)
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        md_bg_color: chex('FAF0E6')
        

        MDBoxLayout:
            # Header Buttons for selecting city and going home
            orientation: 'vertical'
            size_hint: (1 , None) 
            pos_hint: {'center_x' : 0.5, 'top' : 0.99 }
            adaptive_height: True
            padding: [ root.header_button_padding , 0 , root.header_button_padding , 0]
            spacing: root.header_button_spacing

            MDBoxLayout:
                size_hint: (1, None)
                orientation: 'horizontal'
                height: root.header_height
                spacing: root.header_button_spacing
                
                AppButton:
                    size_hint: (None , 1)
                    width: root.header_height
                    md_bg_color: chex("#352F44")
                    padding: root.header_button_padding
                    on_release: root.go_to_home()

                    Image:
                        source: root.home_icon
                        allow_stretch: False
                        keep_ratio: True
                        size_hint: 1, 1
                
                AppButton:
                    size_hint: (1, 1)
                    md_bg_color: chex("#FFFFFF")
                    padding: root.header_button_padding
                    on_release: root.select_available_plan()

                    Label:
                        size_hint: 1, 1
                        text: root.selected_plan
                        font_size: root.header_font_size
                        color: chex("#26221F")
                        font_name: 'p_light'
                        text_size: self.size
                        halign: 'left'
                        valign: 'middle'

                    Image:
                        source: root.bag_icon
                        size_hint: (None , 1)
                        width: root.header_height
                        allow_stretch: False
                        keep_ratio: True
                        

            MDBoxLayout:
                # Header Buttons for selecting plan and how to use
                size_hint: (1, None)
                orientation: 'horizontal'
                height: root.header_height
                spacing: root.header_button_spacing
                
                AppButton:
                    size_hint: (None , 1)
                    width: root.header_height
                    md_bg_color: chex("#352F44")
                    padding: root.header_button_padding
                    on_release: root.change_map_source()

                    Image:
                        source: root.change_map_icon
                        allow_stretch: False
                        keep_ratio: True
                        size_hint: 1, 1
                
                Widget:
                    size_hint: (1, 1)
                # AppButton:
                #     size_hint: (1, 1)
                #     md_bg_color: chex("#5C5470")
                #     padding: root.header_button_padding

                #     Label:
                #         size_hint: 1, 1
                #         text: root.selected_plan
                #         font_size: root.header_font_size
                #         color: chex("#FAF0E6")
                #         font_name: 'p_bold'
                #         text_size: self.size
                #         halign: 'left'
                #         valign: 'middle'

                #     Image:
                #         source: root.bag_icon
                #         size_hint: (None , 1)
                #         width: root.header_height
                #         allow_stretch: False
                #         keep_ratio: True


            # MDBoxLayout:
            #         # Header Buttons for selecting plan and how to use
            #     size_hint: (1, None)
            #     orientation: 'horizontal'
            #     height: root.header_height
            #     spacing: root.header_button_spacing
                
            #     AppButton:
            #         size_hint: (None , 1)
            #         width: root.header_height
            #         md_bg_color: chex("#352F44")
            #         padding: root.header_button_padding
            #         on_release: root.change_map_source()

            #         Image:
            #             source: root.change_map_icon
            #             allow_stretch: False
            #             keep_ratio: True
            #             size_hint: 1, 1

            #     Widget:
            #         size_hint: (1, 1)

        


        AddPlanInformation:
            # Header Buttons for selecting city and going home
            id: add_plan_information
            size_hint: (1 , None)
            pos_hint: {'center_x' : 0.5, 'y': 0 }
            height: root.footer_height



<AddPlanInformation>:
    
    plan_name_label : plan_name_label

    theme_elevation_level: "Custom"
    elevation_level: 2
    theme_shadow_offset: "Custom"
    shadow_offset: 0, 3
    theme_shadow_softness: "Custom"
    shadow_softness: 12
    shadow_radius: root.content_background_radius
    radius: root.content_background_radius
    orientation: 'vertical'

    Widget:
        size_hint: (1 , 0.05)
    Label:
        size_hint: 1, 0.2
        text: "Plan Selected Information"
        font_size: root.header_font_size
        color: chex("#352F44")
        font_name: 'p_bold'
        text_size: self.size
        halign: 'left'
        valign: 'middle'
        pos_hint: {'x' : 0.05}

        # canvas.before:
        #     Color:
        #         rgba: chex("#EF5555")
        #     Rectangle:
        #         pos: self.pos
        #         size: self.size
    
    Widget:
        size_hint: (1 , 0.05)

    BoxLayout:
        size_hint: (1 , 0.1)
        orientation: 'horizontal'

        Widget:
            size_hint: 0.1 , 1
        Image:
            size_hint: None , 1
            width: self.parent.height
            allow_stretch: False
            keep_ratio: True
            source: root.bag_icon
        
        Widget:
            size_hint: 0.05 , 1
        
        Label:
            id: plan_name_label
            size_hint: None , 1 
            text: "Name :"
            font_size: root.header_font_size
            color: chex("#352F44")
            font_name: 'p_bold'
            text_size: None, self.height
            halign: 'left'
            valign: 'middle' 
            width: self.texture_size[0]

        Widget:
            size_hint: 0.02 , 1
            
        Label:
            id: plan_name_label
            size_hint: 0.83, 1
            text: root.plan_name_text 
            font_size: root.header_font_size
            color: chex("#352F44")
            font_name: 'p_light'
            text_size: self.size
            halign: 'left'
            valign: 'middle'
            markup: True


    Widget:
        size_hint: (1 , 0.05)

    BoxLayout:
        size_hint: (1 , 0.1)
        orientation: 'horizontal'

        Widget:
            size_hint: 0.1 , 1
        Image:
            size_hint: None , 1
            width: self.parent.height
            allow_stretch: False
            keep_ratio: True
            source: root.bag_icon
        
        Widget:
            size_hint: 0.05 , 1
        
        Label:
            id: plan_name_label
            size_hint: None , 1 
            text: "Name :"
            font_size: root.header_font_size
            color: chex("#352F44")
            font_name: 'p_bold'
            text_size: None, self.height
            halign: 'left'
            valign: 'middle' 
            width: self.texture_size[0]

        Widget:
            size_hint: 0.02 , 1
            
        Label:
            id: plan_name_label
            size_hint: 0.83, 1
            text: root.plan_name_text 
            font_size: root.header_font_size
            color: chex("#352F44")
            font_name: 'p_light'
            text_size: self.size
            halign: 'left'
            valign: 'middle'
            markup: True
 
    
    Widget:
        size_hint: (1 , 0.05)

    BoxLayout:
        size_hint: (1 , 0.1)
        orientation: 'horizontal'

        Widget:
            size_hint: 0.1 , 1
        Image:
            size_hint: None , 1
            width: self.parent.height
            allow_stretch: False
            keep_ratio: True
            source: root.bag_icon
        
        Widget:
            size_hint: 0.05 , 1
        
        Label:
            id: plan_name_label
            size_hint: None , 1 
            text: "Name :"
            font_size: root.header_font_size
            color: chex("#352F44")
            font_name: 'p_bold'
            text_size: None, self.height
            halign: 'left'
            valign: 'middle' 
            width: self.texture_size[0]

        Widget:
            size_hint: 0.02 , 1
            
        Label:
            id: plan_name_label
            size_hint: 0.83, 1
            text: root.plan_name_text 
            font_size: root.header_font_size
            color: chex("#352F44")
            font_name: 'p_light'
            text_size: self.size
            halign: 'left'
            valign: 'middle'
            markup: True


    Widget:
        size_hint: (1 , 0.05)

    BoxLayout:
        size_hint: ( 1, 0.15)

        Widget:
            size_hint: (0.05 , 1)
        AppButton:
            size_hint: (0.425 , 1)
            md_bg_color: chex("5C5470")
            shadow_radius: root.button_background_radius
            radius: root.button_background_radius

            Label:
                text: "Verify Selected Plan"
                font_size: root.content_font_size
                color: chex("#FFFFFF")
                font_name: 'p_bold'

        Widget:
            size_hint: (0.05 , 1)
        AppButton:
            size_hint: (0.425 , 1)
            md_bg_color: chex("05B51A")
            shadow_radius: root.button_background_radius
            radius: root.button_background_radius
            on_release: root.proceed_to_payment()
 
            Label:
                text: "Proceed to Payment"
                font_size: root.content_font_size
                color: chex("#FFFFFF")
                font_name: 'p_bold'
                

        Widget:
            size_hint: (0.05 , 1)


    Widget:
        size_hint: (1 , 0.1)
