<ForgotAccountScreen>:
    header_buttons : header_buttons
    username_text_input : username_text_input
    new_password_text_input : new_password_text_input
    retype_new_password_text_input : retype_new_password_text_input
    submit_button : submit_button
    BoxLayout:
        orientation: 'vertical' 

        
        MDBoxLayout:
            size_hint: 1 , 0.8
            md_bg_color: chex("#B9B4C7")
            radius: root.adaptive_radius

            ScrollView:
                size_hint: 1 , 1

                MDGridLayout:
                    size_hint: 1, None
                    adaptive_height: True
                    cols: 1
                    padding: [20, 0 , 20 , 0]

                    Widget:
                        size_hint: 1, None
                        height: 25
                    
                    HeaderButtons:
                        id: header_buttons
                    Widget:
                        size_hint: 1, None
                        height: 15
        

                    BoxLayout:
                        size_hint: 1, None
                        orientation: 'horizontal'
                        height: 300


                        Image:
                            allow_stretch: True
                            keep_ratio: True
                            source: root.forgot_account_logo
                            size_hint: (0.5, 1)

                        BoxLayout:
                            size_hint: (0.5, 1)
                            orientation: 'vertical'
                            spacing: 0
                            padding: [0 , 0 , 20 , 0]
                            
                            Widget:
                                size_hint: (1, 0.2)
                            Label:
                                size_hint: (1 , 0.25)
                                font_size: root.forgot_account_title_font_size
                                halign: 'left'
                                valign: 'middle'  # optional, keeps vertical centering
                                text_size: self.size
                                font_name: 'p_extrabold'
                                text: 'Reset Your Password'
                                color: chex("#352F44")
                            Widget:
                                size_hint: (1, 0.05)
                            Label:
                                size_hint: (1, 0.50)
                                font_size: root.forgot_account_content_font_size
                                halign: 'left'
                                valign: 'top'
                                text_size: self.size
                                font_name: 'p_light'
                                color: chex("#352F44")
                                text: "Enter your username and a new password below. We'll send a verification link to your email—click that link to confirm and complete the change."
                    Widget:
                        size_hint: 1, None
                        height: 15
 
                    Label:
                        size_hint: 1, None
                        height: 35
                        font_size: root.h1_font_size
                        halign: 'left'
                        valign: 'middle'  # optional, keeps vertical centering
                        text_size: self.size
                        font_name: 'p_bold'
                        text: 'Account Security Information'
                        color: chex("#FFFFFF")
                    Widget:
                        size_hint: 1, None
                        height: 15
                    OneLineInput:
                        id: username_text_input
                        size_hint: 1, None
                        height: 35
                    Widget:
                        size_hint: 1, None
                        height: 10
                    OneLineInput:
                        id: new_password_text_input
                        size_hint: 1, None
                        height: 35
                    Widget:
                        size_hint: 1, None
                        height: 10
                    OneLineInput:
                        id: retype_new_password_text_input
                        size_hint: 1, None
                        height: 35
                    Widget:
                        size_hint: 1, None
                        height: 35
                    BoxLayout:
                        size_hint: 1 , None
                        height: 35

                        Widget:
                            size_hint: 0.6, 1
                        
                        AppButton:
                            id: submit_button
                            size_hint: 0.4, 1
                            Label:
                                size_hint: 1, 1
                                text: "Update Password"
                                font_size: root.submit_button_font_size
                                font_name: 'p_bold'

                    Widget:
                        size_hint: 1, None
                        height: 50

        BoxLayout:
            size_hint: (1, 0.2)
            orientation: 'horizontal'
            padding: 10

            Image:
                allow_stretch: True
                keep_ratio: True
                source: root.login_logo
                size_hint: (0.5, 1)
            
            BoxLayout:
                size_hint: (0.5, 1)
                orientation: 'vertical'
                spacing: 0
                
                Widget:
                    size_hint: (1, 0.2)
                Label:
                    size_hint: (1 , 0.2)
                    font_size: root.info_title_font_size
                    halign: 'left'
                    valign: 'middle'  # optional, keeps vertical centering
                    text_size: self.size
                    font_name: 'p_regular'
                    text: 'Your Connection, Your Control'
                Widget:
                    size_hint: (1, 0.05)
                Label:
                    size_hint: (1, 0.55)
                    font_size: root.info_content_font_size
                    halign: 'left'
                    valign: 'top'
                    text_size: self.size
                    font_name: 'p_extralight'
                    text: 'Stay in the loop—track your router issues, monitor ticket updates, and manage your account, all in one smart app designed to keep your internet running smoothly.'
                    
        